SERVER_NAME: "127.0.0.1:5000"
SQLALCHEMY_DATABASE_URI: "mysql+mysqlconnector://root:dbaRoot#123@localhost:3306/glcaptest"
TESTING: "True"
DEST_FOLDER: "/Users/apple/Documents/GreatLearning/Captsone/testdata"

MYSQL_CONNECTION: "localhost"
MYSQL_DB: "glcaptest"
MYSQL_USER: "root"
MYSQL_PASS: "dbaRoot#123"

LOGGING_FILEPATH: "/Users/apple/Documents/GreatLearning/Captsone/testdata/filemanager.log"
